apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  namespace: app
spec:
  selector:
    app: app-1
  ports:
    - port: 3000

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-1-rs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: austinloveless/app_1:latest
          env:
            - name: APP_2_SERVICE_HOST
              value: app-2-service
            - name: APP_2_SERVICE_PORT
              value: "3000"
            - name: APP_2_SERVICE_PATH
              value: /
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-2-service
  namespace: app
spec:
  selector:
    app: app-2
  ports:
    - port: 3001

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-2-rs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: app-2
          image: austinloveless/app_2:latest
          ports:
            - containerPort: 3000
