apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    name: app
---
apiVersion: v1
kind: Service
metadata:
  name: app-1-service
  namespace: app
spec:
  selector:
    app: app-1
  ports:
    - name: app-1
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-1-rs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
        - name: app-1
          image: austinloveless/app_1:latest
          env:
            - name: APP_2_SERVICE_HOST
              value: app-2-service
            - name: APP_2_SERVICE_PORT
              value: "3000"
            - name: APP_2_SERVICE_PATH
              value: /
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-2-service
  namespace: app
spec:
  selector:
    app: app-2
  ports:
    - name: app-2
      port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-2-rs
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      containers:
        - name: app-2
          image: austinloveless/app_2:latest
          ports:
            - containerPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-1-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-1-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-2-ingress
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-2-service
                port:
                  number: 80
