apiVersion: v1
kind: Namespace
metadata:
  name: crypto
  labels:
    name: crypto

---
apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
  namespace: crypto
type: Opaque
data:
  ACCESS_KEY_ID: BASE64 encoded AWS ACCESS_KEY_ID
  SECRET_ACCESS_KEY: BASE64 encoded AWS SECRET_ACCESS_KEY

########
# CRYPTO-CLIENT #1
########
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: crypto-client-rs-1
  namespace: crypto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-client
  template:
    metadata:
      labels:
        app: crypto-client
    spec:
      containers:
        - name: crypto-client
          image: austinloveless/crypto-client
          envFrom:
            - secretRef:
                name: client-secrets
            - configMapRef:
                name: client-configmap-1
          env:
            - name: SVC
              value: crypto-server-service
            - name: NAMESPACE
              value: crypto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap-1
  namespace: crypto
data:
  DATEBASE_NAME: AWSMeetupGroupESDB
  TABLE_NAME: CryptoData
  AWS_REGION: us-east-1
  CRYPTO_SYMBOL: BCH

########
# CRYPTO-CLIENT #2
########
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: crypto-client-rs-2
  namespace: crypto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-client
  template:
    metadata:
      labels:
        app: crypto-client
    spec:
      containers:
        - name: crypto-client
          image: austinloveless/crypto-client
          envFrom:
            - secretRef:
                name: client-secrets
            - configMapRef:
                name: client-configmap-2
          env:
            - name: SVC
              value: crypto-server-service
            - name: NAMESPACE
              value: crypto

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap-2
  namespace: crypto
data:
  DATEBASE_NAME: AWSMeetupGroupESDB
  TABLE_NAME: CryptoData
  AWS_REGION: us-east-1
  CRYPTO_SYMBOL: ETH

########
# CRYPTO-CLIENT #3
########
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: crypto-client-rs-3
  namespace: crypto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crypto-client
  template:
    metadata:
      labels:
        app: crypto-client
    spec:
      containers:
        - name: crypto-client
          image: austinloveless/crypto-client
          envFrom:
            - secretRef:
                name: client-secrets
            - configMapRef:
                name: client-configmap-3
          env:
            - name: SVC
              value: crypto-server-service
            - name: NAMESPACE
              value: crypto
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-configmap-3
  namespace: crypto
data:
  DATEBASE_NAME: AWSMeetupGroupESDB
  TABLE_NAME: CryptoData
  AWS_REGION: us-east-1
  CRYPTO_SYMBOL: LTC

########
# CRYPTO-SERVER
########
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: crypto-server-rs
  namespace: crypto
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crypto-server
  template:
    metadata:
      labels:
        app: crypto-server
    spec:
      containers:
        - name: crypto-server
          image: austinloveless/crypto-server
          envFrom:
            - secretRef:
                name: server-secrets
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-server-service
  namespace: crypto
spec:
  selector:
    app: crypto-server
  ports:
    - name: crypto-server
      port: 80
      targetPort: 8080
      nodePort: 32001
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: server-secrets
  namespace: crypto
type: Opaque
data:
  API_KEY: BASE64 encoded API_KEY
